# Generated by Django 5.0.6 on 2024-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=160)),
                ('salary', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('hire_date', models.DateTimeField()),
            ],
        ),
    ]
